In [22]:
import eikon as ek 
import pandas as pd 
import numpy as np 
import seaborn as sns 
import scipy.stats as st
import matplotlib.pyplot as plt 
%matplotlib inline 
import time

In [6]:
ek.set_app_key('252654a1a1704474af2f41b74d6ecbdcaf544a78')

In [18]:
barc = ek.get_data('0#BARC*.EX',['STRIKE_PRC','EXPIR_DATE','PUTCALLIND','CF_CLOSE'])
barc[0]['Instrument'] = barc[0]['Instrument'].apply(lambda x: x.replace("/", ""))
barc[0]

/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/data_grid.py:247: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data = pd.np.array([[get_data_value(value) for value in row] for row in data_dict['data']])

         Instrument  STRIKE_PRC  EXPIR_DATE PUTCALLIND  CF_CLOSE
0            BARC.L         NaN        None       None    118.58
1     BARC010aG0.EX         1.0  2020-07-17       CALL    117.50
2     BARC010aS0.EX         1.0  2020-07-17       PUT        NaN
3     BARC840aG0.EX        84.0  2020-07-17       CALL     34.50
4     BARC840aS0.EX        84.0  2020-07-17       PUT       0.25
..              ...         ...         ...        ...       ...
266  BARC1600aR2.EX       160.0  2022-06-17       PUT      57.25
267  BARC1800aF2.EX       180.0  2022-06-17       CALL      7.25
268  BARC1800aR2.EX       180.0  2022-06-17       PUT      73.50
269  BARC2000aF2.EX       200.0  2022-06-17       CALL      4.75
270  BARC2000aR2.EX       200.0  2022-06-17       PUT      91.00

[271 rows x 5 columns]

In [19]:
barc[0].to_csv('barc.csv', index=False)
pd.read_csv('barc.csv')

         Instrument  STRIKE_PRC  EXPIR_DATE PUTCALLIND  CF_CLOSE
0            BARC.L         NaN         NaN        NaN    118.58
1     BARC010aG0.EX         1.0  2020-07-17       CALL    117.50
2     BARC010aS0.EX         1.0  2020-07-17       PUT        NaN
3     BARC840aG0.EX        84.0  2020-07-17       CALL     34.50
4     BARC840aS0.EX        84.0  2020-07-17       PUT       0.25
..              ...         ...         ...        ...       ...
266  BARC1600aR2.EX       160.0  2022-06-17       PUT      57.25
267  BARC1800aF2.EX       180.0  2022-06-17       CALL      7.25
268  BARC1800aR2.EX       180.0  2022-06-17       PUT      73.50
269  BARC2000aF2.EX       200.0  2022-06-17       CALL      4.75
270  BARC2000aR2.EX       200.0  2022-06-17       PUT      91.00

[271 rows x 5 columns]

In [20]:
barc = barc[0].dropna()
barc

         Instrument  STRIKE_PRC  EXPIR_DATE PUTCALLIND  CF_CLOSE
1     BARC010aG0.EX         1.0  2020-07-17       CALL    117.50
3     BARC840aG0.EX        84.0  2020-07-17       CALL     34.50
4     BARC840aS0.EX        84.0  2020-07-17       PUT       0.25
5     BARC860aG0.EX        86.0  2020-07-17       CALL     32.50
6     BARC860aS0.EX        86.0  2020-07-17       PUT       0.25
..              ...         ...         ...        ...       ...
266  BARC1600aR2.EX       160.0  2022-06-17       PUT      57.25
267  BARC1800aF2.EX       180.0  2022-06-17       CALL      7.25
268  BARC1800aR2.EX       180.0  2022-06-17       PUT      73.50
269  BARC2000aF2.EX       200.0  2022-06-17       CALL      4.75
270  BARC2000aR2.EX       200.0  2022-06-17       PUT      91.00

[267 rows x 5 columns]

In [21]:
list(set(barc['Instrument']))

['BARC840aR2.EX',
 'BARC2400aR1.EX',
 'BARC1200aX0.EX',
 'BARC840aR1.EX',
 'BARC720aL0.EX',
 'BARC880aC1.EX',
 'BARC1100aO1.EX',
 'BARC1500aF1.EX',
 'BARC1500aH0.EX',
 'BARC840aF2.EX',
 'BARC1100aU0.EX',
 'BARC920aH0.EX',
 'BARC720aI0.EX',
 'BARC880aF1.EX',
 'BARC840aO1.EX',
 'BARC1300aX0.EX',
 'BARC1000aR1.EX',
 'BARC1300aR1.EX',
 'BARC1400aT0.EX',
 'BARC1050aU0.EX',
 'BARC1600aR2.EX',
 'BARC880aO1.EX',
 'BARC800aU0.EX',
 'BARC600aX1.EX',
 'BARC1100aG0.EX',
 'BARC840aS0.EX',
 'BARC1600aL1.EX',
 'BARC1600aX0.EX',
 'BARC1350aS0.EX',
 'BARC1000aF1.EX',
 'BARC1350aG0.EX',
 'BARC2000aX0.EX',
 'BARC1700aL0.EX',
 'BARC1400aR1.EX',
 'BARC900aS0.EX',
 'BARC1000aI0.EX',
 'BARC1400aX0.EX',
 'BARC1600aX1.EX',
 'BARC010aG0.EX',
 'BARC2000aL1.EX',
 'BARC1700aU0.EX',
 'BARC1150aU0.EX',
 'BARC760aR1.EX',
 'BARC680aX1.EX',
 'BARC1000aC1.EX',
 'BARC1100aC1.EX',
 'BARC880aS0.EX',
 'BARC010aL0.EX',
 'BARC960aC1.EX',
 'BARC2000aF2.EX',
 'BARC1300aL0.EX',
 'BARC2000aF1.EX',
 'BARC880aI0.EX',
 'BARC1400aC1.EX',
 'BARC960aR1.EX',
 'BARC980aG0.EX',
 'BARC960aO1.EX',
 'BARC1200aC1.EX',
 'BARC1000aX0.EX',
 'BARC680aU0.EX',
 'BARC920aI0.EX',
 'BARC1350aU0.EX',
 'BARC960aL0.EX',
 'BARC760aL0.EX',
 'BARC1600aL0.EX',
 'BARC920aU0.EX',
 'BARC1100aT0.EX',
 'BARC640aU0.EX',
 'BARC1000aH0.EX',
 'BARC840aX0.EX',
 'BARC010aI0.EX',
 'BARC1400aF1.EX',
 'BARC760aL1.EX',
 'BARC840aU0.EX',
 'BARC1500aU0.EX',
 'BARC840aL1.EX',
 'BARC1000aR2.EX',
 'BARC880aX0.EX',
 'BARC980aU0.EX',
 'BARC720aO1.EX',
 'BARC960aF1.EX',
 'BARC800aO1.EX',
 'BARC1400aX1.EX',
 'BARC760aR2.EX',
 'BARC1250aS0.EX',
 'BARC1050aI0.EX',
 'BARC2000aX1.EX',
 'BARC1400aF2.EX',
 'BARC960aI0.EX',
 'BARC900aG0.EX',
 'BARC720aC1.EX',
 'BARC1200aF2.EX',
 'BARC1000aU0.EX',
 'BARC1000aL0.EX',
 'BARC1000aX1.EX',
 'BARC960aT0.EX',
 'BARC1300aC1.EX',
 'BARC720aU0.EX',
 'BARC1000aL1.EX',
 'BARC960aG0.EX',
 'BARC600aR1.EX',
 'BARC960aU0.EX',
 'BARC2000aL0.EX',
 'BARC940aT0.EX',
 'BARC600aL1.EX',
 'BARC1600aF1.EX',
 'BARC1450aT0.EX',
 'BARC1400aO1.EX',
 'BARC640aX0.EX',
 'BARC920aL1.EX',
 'BARC1250aG0.EX',
 'BARC1500aT0.EX',
 'BARC720aX0.EX',
 'BARC680aC1.EX',
 'BARC1050aH0.EX',
 'BARC1150aT0.EX',
 'BARC1100aR1.EX',
 'BARC2000aR1.EX',
 'BARC2400aF1.EX',
 'BARC1600aO1.EX',
 'BARC1050aS0.EX',
 'BARC880aR1.EX',
 'BARC1500aO1.EX',
 'BARC920aX0.EX',
 'BARC920aS0.EX',
 'BARC1100aH0.EX',
 'BARC980aS0.EX',
 'BARC880aU0.EX',
 'BARC1600aI0.EX',
 'BARC800aI0.EX',
 'BARC520aF1.EX',
 'BARC960aS0.EX',
 'BARC1300aG0.EX',
 'BARC1500aI0.EX',
 'BARC1800aR1.EX',
 'BARC2000aR2.EX',
 'BARC980aH0.EX',
 'BARC520aR1.EX',
 'BARC920aG0.EX',
 'BARC800aC1.EX',
 'BARC1600aC1.EX',
 'BARC760aX0.EX',
 'BARC1200aG0.EX',
 'BARC760aF1.EX',
 'BARC680aX0.EX',
 'BARC1200aS0.EX',
 'BARC1400aG0.EX',
 'BARC1100aS0.EX',
 'BARC1300aH0.EX',
 'BARC1350aI0.EX',
 'BARC1500aX0.EX',
 'BARC1700aC1.EX',
 'BARC1800aU0.EX',
 'BARC920aC1.EX',
 'BARC1800aL1.EX',
 'BARC860aS0.EX',
 'BARC1700aX0.EX',
 'BARC1200aX1.EX',
 'BARC1200aL1.EX',
 'BARC980aT0.EX',
 'BARC1350aT0.EX',
 'BARC1700aI0.EX',
 'BARC1400aH0.EX',
 'BARC600aF1.EX',
 'BARC1100aX0.EX',
 'BARC1150aH0.EX',
 'BARC880aG0.EX',
 'BARC1300aF1.EX',
 'BARC1000aF2.EX',
 'BARC1300aO1.EX',
 'BARC920aF2.EX',
 'BARC840aG0.EX',
 'BARC800aX0.EX',
 'BARC680aR1.EX',
 'BARC1000aS0.EX',
 'BARC1200aT0.EX',
 'BARC1200aF1.EX',
 'BARC940aS0.EX',
 'BARC680aF1.EX',
 'BARC520aL1.EX',
 'BARC840aL0.EX',
 'BARC520aX1.EX',
 'BARC1800aX1.EX',
 'BARC900aH0.EX',
 'BARC920aL0.EX',
 'BARC1250aI0.EX',
 'BARC1800aF1.EX',
 'BARC760aF2.EX',
 'BARC1300aS0.EX',
 'BARC1300aI0.EX',
 'BARC760aI0.EX',
 'BARC680aO1.EX',
 'BARC1800aI0.EX',
 'BARC1400aL1.EX',
 'BARC2400aX1.EX',
 'BARC1450aH0.EX',
 'BARC1200aU0.EX',
 'BARC1400aU0.EX',
 'BARC1400aR2.EX',
 'BARC1300aU0.EX',
 'BARC840aC1.EX',
 'BARC840aF1.EX',
 'BARC940aG0.EX',
 'BARC680aI0.EX',
 'BARC760aU0.EX',
 'BARC960aX0.EX',
 'BARC1400aL0.EX',
 'BARC920aT0.EX',
 'BARC1400aI0.EX',
 'BARC1050aG0.EX',
 'BARC1700aO1.EX',
 'BARC840aX1.EX',
 'BARC1250aT0.EX',
 'BARC1350aH0.EX',
 'BARC1200aR2.EX',
 'BARC760aO1.EX',
 'BARC920aR1.EX',
 'BARC920aR2.EX',
 'BARC760aC1.EX',
 'BARC1100aL0.EX',
 'BARC1050aT0.EX',
 'BARC1150aG0.EX',
 'BARC640aL0.EX',
 'BARC860aG0.EX',
 'BARC1150aS0.EX',
 'BARC1200aO1.EX',
 'BARC1000aO1.EX',
 'BARC640aC1.EX',
 'BARC840aI0.EX',
 'BARC1200aR1.EX',
 'BARC1600aU0.EX',
 'BARC1800aX0.EX',
 'BARC1500aR1.EX',
 'BARC1800aL0.EX',
 'BARC2400aL1.EX',
 'BARC1200aI0.EX',
 'BARC640aI0.EX',
 'BARC1400aS0.EX',
 'BARC1800aR2.EX',
 'BARC1150aI0.EX',
 'BARC1200aL0.EX',
 'BARC1600aR1.EX',
 'BARC1800aF2.EX',
 'BARC1000aT0.EX',
 'BARC900aT0.EX',
 'BARC1250aU0.EX',
 'BARC1200aH0.EX',
 'BARC1250aH0.EX',
 'BARC640aO1.EX',
 'BARC1100aF1.EX',
 'BARC1100aI0.EX',
 'BARC1000aG0.EX',
 'BARC1500aL0.EX',
 'BARC960aH0.EX',
 'BARC1500aC1.EX',
 'BARC1300aT0.EX',
 'BARC920aX1.EX',
 'BARC940aH0.EX',
 'BARC880aL0.EX',
 'BARC920aO1.EX',
 'BARC920aF1.EX',
 'BARC980aI0.EX',
 'BARC680aL1.EX',
 'BARC1600aF2.EX',
 'BARC760aX1.EX',
 'BARC800aL0.EX',
 'BARC680aL0.EX']

In [8]:
import bs4 as bs
import pickle 
import requests 
import lxml 

def tickersFTSE(): 
    resp = requests.get('https://en.wikipedia.org/wiki/FTSE_100_Index#Constituents_in_March_2020')
    soup = bs.BeautifulSoup(resp.text)
    table = soup.findAll('table', {'class': 'wikitable sortable'})[1]
    tickers = []
    for row in table.findAll('tr')[1:]: 
        ticker = row.findAll('td')[1].text
        ticker = ticker.replace("\n","")
        tickers.append(ticker)
        
    with open('ftse100tickers.pickle', 'wb') as f: 
        pickle.dump(tickers, f)
    
    return tickers 

tickersFTSE()

['III',
 'ADM',
 'AAL',
 'ANTO',
 'AHT',
 'ABF',
 'AZN',
 'AUTO',
 'AVST',
 'AVV',
 'AV',
 'BA',
 'BARC',
 'BDEV',
 'BKG',
 'BHP',
 'BP',
 'BATS',
 'BLND',
 'BT-A',
 'BNZL',
 'BRBY',
 'CCH',
 'CPG',
 'CRH',
 'CRDA',
 'DCC',
 'DGE',
 'EVR',
 'EXPN',
 'FERG',
 'FLTR',
 'FRES',
 'GSK',
 'GLEN',
 'GVC',
 'HLMA',
 'HL',
 'HIK',
 'HSV',
 'HSBA',
 'IMB',
 'INF',
 'IHG',
 'ICP',
 'IAG',
 'ITRK',
 'ITV',
 'JD',
 'JMAT',
 'JET',
 'KGF',
 'LAND',
 'LGEN',
 'LLOY',
 'LSE',
 'MNG',
 'MRO',
 'MNDI',
 'MRW',
 'NG',
 'NXT',
 'OCDO',
 'PSON',
 'PNN',
 'PSN',
 'PHNX',
 'POLY',
 'PRU',
 'RB',
 'REL',
 'RTO',
 'RIO',
 'RMV',
 'RR',
 'RBS',
 'RDSA',
 'RSA',
 'SGE',
 'SBRY',
 'SDR',
 'SMT',
 'SGRO',
 'SVT',
 'SN',
 'SMDS',
 'SMIN',
 'SKG',
 'SPX',
 'SSE',
 'STAN',
 'SLA',
 'STJ',
 'TW',
 'TSCO',
 'ULVR',
 'UU',
 'VOD',
 'WTB',
 'WPP']

In [9]:
ftse100 = pd.DataFrame(tickersFTSE())
ftse100.to_csv('ftse100.csv', index=False, header=False)
pd.read_csv('ftse100.csv', header=None)

       0
0    III
1    ADM
2    AAL
3   ANTO
4    AHT
..   ...
95  ULVR
96    UU
97   VOD
98   WTB
99   WPP

[100 rows x 1 columns]

In [24]:
def opInfo(ticker='BARC'):
    return ek.get_data('0#'+ticker+'*.EX',['STRIKE_PRC','EXPIR_DATE','PUTCALLIND','CF_CLOSE'])[0]

def getOpPrices(ticker='BARC'):
    fst = True 
    instr = list(set(ek.get_data('0#'+ticker+'*.EX',['STRIKE_PRC','EXPIR_DATE','PUTCALLIND','CF_CLOSE'])[0]['Instrument']))
    for i in instr: 
        try: 
            if fst:
                a = ek.get_timeseries(i, 'CLOSE',
                                  start_date='20100101',end_date='20200601').reset_index()
                a.insert(0, 'OPTION_ID', a.columns.name)
                fst = False
            else: 
                b = ek.get_timeseries(i,'CLOSE',
                                  start_date='20100101',end_date='20200601').reset_index()
                b.insert(0, 'OPTION_ID', b.columns.name)
                a = a.append(b)
        except: 
            pass
        time.sleep(0.2)
    return a

In [25]:
opInfo()

/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/data_grid.py:247: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data = pd.np.array([[get_data_value(value) for value in row] for row in data_dict['data']])

          Instrument  STRIKE_PRC  EXPIR_DATE PUTCALLIND  CF_CLOSE
0            /BARC.L         NaN        None       None    118.58
1     /BARC010aG0.EX         1.0  2020-07-17       CALL    117.50
2     /BARC010aS0.EX         1.0  2020-07-17       PUT        NaN
3     /BARC840aG0.EX        84.0  2020-07-17       CALL     34.50
4     /BARC840aS0.EX        84.0  2020-07-17       PUT       0.25
..               ...         ...         ...        ...       ...
266  /BARC1600aR2.EX       160.0  2022-06-17       PUT      57.25
267  /BARC1800aF2.EX       180.0  2022-06-17       CALL      7.25
268  /BARC1800aR2.EX       180.0  2022-06-17       PUT      73.50
269  /BARC2000aF2.EX       200.0  2022-06-17       CALL      4.75
270  /BARC2000aR2.EX       200.0  2022-06-17       PUT      91.00

[271 rows x 5 columns]

In [26]:
getOpPrices()

/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/data_grid.py:247: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data = pd.np.array([[get_data_value(value) for value in row] for row in data_dict['data']])
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:282: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.array(timeseries['dataPoints'])
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:284: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  timestamps = pd.np.array([tz_replacer(value) for value in datapoints[:, timestamp_index]],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:286: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.delete(datapoints, pd.np.s_[timestamp_index],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:209: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data_frame = data_frame.fillna(pd.np.nan)
2020-07-17 16:14:48,045 P[33415] [MainThread 4467940800] Error with /BARC2400aR1.EX: No data available for the requested date range
2020-07-17 16:14:48,045 P[33415] [MainThread 4467940800] /BARC2400aR1.EX: No data available for the requested date range |
2020-07-17 16:14:58,474 P[33415] [MainThread 4467940800] Error with /BARC1500aR1.EX: No data available for the requested date range
2020-07-17 16:14:58,475 P[33415] [MainThread 4467940800] /BARC1500aR1.EX: No data available for the requested date range |
2020-07-17 16:15:15,852 P[33415] [MainThread 4467940800] Error with /BARC1350aI0.EX: No data available for the requested date range
2020-07-17 16:15:15,854 P[33415] [MainThread 4467940800] /BARC1350aI0.EX: No data available for the requested date range |
2020-07-17 16:15:18,709 P[33415] [MainThread 4467940800] Error with /BARC010aU0.EX: No data available for the requested date range
2020-07-17 16:15:18,710 P[33415] [MainThread 4467940800] /BARC010aU0.EX: No data available for the requested date range |
2020-07-17 16:15:23,712 P[33415] [MainThread 4467940800] Error with /BARC1600aR2.EX: No data available for the requested date range
2020-07-17 16:15:23,713 P[33415] [MainThread 4467940800] /BARC1600aR2.EX: No data available for the requested date range |
2020-07-17 16:15:53,780 P[33415] [MainThread 4467940800] Error with /BARC1000aR2.EX: No data available for the requested date range
2020-07-17 16:15:53,781 P[33415] [MainThread 4467940800] /BARC1000aR2.EX: No data available for the requested date range |
2020-07-17 16:15:56,666 P[33415] [MainThread 4467940800] Error with /BARC1150aI0.EX: No data available for the requested date range
2020-07-17 16:15:56,668 P[33415] [MainThread 4467940800] /BARC1150aI0.EX: No data available for the requested date range |
2020-07-17 16:15:58,981 P[33415] [MainThread 4467940800] Error with /BARC1250aU0.EX: No data available for the requested date range
2020-07-17 16:15:58,982 P[33415] [MainThread 4467940800] /BARC1250aU0.EX: No data available for the requested date range |
2020-07-17 16:16:05,694 P[33415] [MainThread 4467940800] Error with /BARC980aI0.EX: No data available for the requested date range
2020-07-17 16:16:05,695 P[33415] [MainThread 4467940800] /BARC980aI0.EX: No data available for the requested date range |
2020-07-17 16:16:06,289 P[33415] [MainThread 4467940800] Error with /BARC1600aF2.EX: No data available for the requested date range
2020-07-17 16:16:06,290 P[33415] [MainThread 4467940800] /BARC1600aF2.EX: No data available for the requested date range |
2020-07-17 16:16:12,360 P[33415] [MainThread 4467940800] Error with /BARC760aR2.EX: No data available for the requested date range
2020-07-17 16:16:12,361 P[33415] [MainThread 4467940800] /BARC760aR2.EX: No data available for the requested date range |
2020-07-17 16:16:18,625 P[33415] [MainThread 4467940800] Error with /BARC1000aF2.EX: No data available for the requested date range
2020-07-17 16:16:18,626 P[33415] [MainThread 4467940800] /BARC1000aF2.EX: No data available for the requested date range |
2020-07-17 16:16:32,411 P[33415] [MainThread 4467940800] Error with /BARC880aF1.EX: No data available for the requested date range
2020-07-17 16:16:32,412 P[33415] [MainThread 4467940800] /BARC880aF1.EX: No data available for the requested date range |
2020-07-17 16:16:33,023 P[33415] [MainThread 4467940800] Error with /BARC010aL0.EX: No data available for the requested date range
2020-07-17 16:16:33,025 P[33415] [MainThread 4467940800] /BARC010aL0.EX: No data available for the requested date range |

KeyboardInterrupt:

In [ ]:
# Collect option info 
def getAllInfo():
    i = 0
    fst = True 
    for t in ftse100[0]:
        print(t)
        try: 
            if fst: 
                a = opInfo(t)
                fst = False
            else:
                a = a.append(opInfo(t))
            a['Instrument'] = a['Instrument'].apply(lambda x: x.replace("/",""))
        except:
            pass
        time.sleep(0.2)

    return a.dropna()

In [ ]:
opPart1 = getAllInfo()
opPart1

In [ ]:
opPart1.to_csv('OpInfo.csv',index=False)
pd.read_csv('OpInfo.csv')

In [ ]:
def getAllPrices():
    fst = True 
    for t in ftse100[0]:
        try: 
            if fst: 
                a = getOpPrices(t)
                fst = False
            else: 
                a = a.append(getOpPrices(t))
        except:
            pass

    a = a.dropna()
    return a

In [ ]:
allP = getAllPrices()
allP

In [ ]:
allP = allP[allP['OPTION_ID'].str[:4] != 'SBRY']
ftse100[0][ftse100[0] == 'SBRY'].index[0]

In [10]:
for t in ftse100[0][ftse100[0][ftse100[0] == 'SBRY'].index[0]:]:
    try: 
        allP = allP.append(getOpPrices(t))
    except:
        pass

    allP = allP.dropna()

allP

NameError: name 'allP' is not defined

In [ ]:
allP.to_csv('OpData.csv', index=False)
pd.read_csv('OpData.csv')

In [ ]:
allInOne = pd.merge(allP, opPart1, how='outer', left_on='OPTION_ID', right_on='Instrument').drop(['Instrument','CF_CLOSE'],axis=1).dropna()
allInOne['Date'] = pd.to_datetime(allInOne['Date'], format='%Y-%m-%d')
allInOne['EXPIR_DATE'] = pd.to_datetime(allInOne['EXPIR_DATE'], format='%Y-%m-%d')
allInOne.insert(0,'Ticker',allInOne['OPTION_ID'].str[:4].str.rstrip('1234567890'))
allInOne

In [ ]:
allInOne.to_csv('allOpData.csv', index=False)
pd.read_csv('allOpData.csv')

In [11]:
stcks = pd.read_csv('opStocks.txt', header=None)
stcks = stcks + '.L'
stcks = list(stcks.values.flatten())
stcks

['AAL.L',
 'AV.L',
 'AZN.L',
 'BARC.L',
 'BP.L',
 'BRBY.L',
 'CPG.L',
 'CRH.L',
 'DGE.L',
 'GLEN.L',
 'GSK.L',
 'HSBA.L',
 'LGEN.L',
 'LLOY.L',
 'MNDI.L',
 'NG.L',
 'OCDO.L',
 'RB.L',
 'RBS.L',
 'RIO.L',
 'RSA.L',
 'SBRY.L',
 'SKG.L',
 'STAN.L',
 'TSCO.L',
 'ULVR.L',
 'VOD.L']

In [12]:
fst = True 
for t in stcks:
    if fst: 
        sData = pd.DataFrame(ek.get_timeseries(t, start_date='2018-12-01', end_date='2020-01-07')['CLOSE'])
        sData['Ticker'] = t.replace('.L','')
        fst = False
    else: 
        d = pd.DataFrame(ek.get_timeseries(t, start_date='2018-12-01', end_date='2020-01-07')['CLOSE'])
        d['Ticker'] = t.replace('.L','')
        sData = sData.append(d)
        time.sleep(0.2)

sDatacopy = sData
sData

/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:282: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.array(timeseries['dataPoints'])
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:284: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  timestamps = pd.np.array([tz_replacer(value) for value in datapoints[:, timestamp_index]],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:286: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.delete(datapoints, pd.np.s_[timestamp_index],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:209: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data_frame = data_frame.fillna(pd.np.nan)

              CLOSE Ticker
Date
2018-12-03  1675.40    AAL
2018-12-04  1660.00    AAL
2018-12-05  1625.00    AAL
2018-12-06  1556.40    AAL
2018-12-07  1607.80    AAL
...             ...    ...
2019-12-31   146.76    VOD
2020-01-02   147.80    VOD
2020-01-03   147.94    VOD
2020-01-06   147.08    VOD
2020-01-07   146.66    VOD

[7452 rows x 2 columns]

In [13]:
sData = sDatacopy
sData

              CLOSE Ticker
Date
2018-12-03  1675.40    AAL
2018-12-04  1660.00    AAL
2018-12-05  1625.00    AAL
2018-12-06  1556.40    AAL
2018-12-07  1607.80    AAL
...             ...    ...
2019-12-31   146.76    VOD
2020-01-02   147.80    VOD
2020-01-03   147.94    VOD
2020-01-06   147.08    VOD
2020-01-07   146.66    VOD

[7452 rows x 2 columns]

In [14]:
sData.columns = ['Price', 'Ticker']
sData['SRet'] = np.log(sData.Price / sData.Price.shift())
sData

              Price Ticker      SRet
Date
2018-12-03  1675.40    AAL       NaN
2018-12-04  1660.00    AAL -0.009234
2018-12-05  1625.00    AAL -0.021310
2018-12-06  1556.40    AAL -0.043132
2018-12-07  1607.80    AAL  0.032491
...             ...    ...       ...
2019-12-31   146.76    VOD -0.012594
2020-01-02   147.80    VOD  0.007061
2020-01-03   147.94    VOD  0.000947
2020-01-06   147.08    VOD -0.005830
2020-01-07   146.66    VOD -0.002860

[7452 rows x 3 columns]

In [15]:
rets = sData.reset_index().pivot('Date', 'Ticker', 'SRet')
rets

Ticker,AAL,AV,AZN,BARC,BP,BRBY,CPG,CRH,DGE,GLEN,...,RB,RBS,RIO,RSA,SBRY,SKG,STAN,TSCO,ULVR,VOD
Date,,,,,,,,,,,,,,,,,,,,,
2018-12-03,NaN,-1.674470,2.690488,-3.845606,1.066393,1.315051,-0.244866,0.176844,-0.070738,-2.359605,...,1.603156,-3.413820,2.721411,-2.097991,-0.611580,2.262845,-1.528811,-1.267878,2.814078,-3.239138
2018-12-04,-0.009234,-0.014682,0.009545,-0.026543,0.009355,-0.025898,-0.001181,-0.037619,0.008463,-0.012713,...,0.005300,-0.020544,0.006463,-0.007739,0.002608,-0.051768,-0.031409,-0.002282,0.011828,-0.017527
2018-12-05,-0.021310,-0.003013,-0.025933,-0.004156,-0.018798,-0.022624,-0.012489,-0.031342,-0.012721,-0.039490,...,-0.033324,0.023702,-0.020474,-0.012284,-0.002281,-0.032790,-0.009585,0.010101,-0.012770,-0.013043
2018-12-06,-0.043132,-0.049746,-0.016158,-0.032975,-0.046014,-0.031858,-0.019946,-0.040109,-0.015771,-0.052492,...,-0.029957,-0.046091,-0.038114,-0.050308,-0.021435,-0.044608,-0.028465,-0.026736,-0.016406,-0.015706
2018-12-07,0.032491,0.008421,-0.004713,0.006760,0.022592,0.009289,0.018449,0.027976,0.005943,0.030895,...,0.009289,-0.009479,0.020006,-0.004342,0.000000,0.023304,0.013407,0.026987,0.021346,0.014355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31,0.000921,-0.003576,-0.006160,-0.003334,-0.014525,-0.007230,-0.007905,-0.003282,-0.001405,-0.008462,...,-0.008287,-0.006636,-0.000888,0.000707,-0.019385,-0.004101,-0.007551,-0.001175,-0.005158,-0.012594
2020-01-02,0.013257,0.011635,0.006943,0.030481,0.019424,-0.001816,0.006855,0.018564,-0.005483,0.023931,...,0.011518,0.016509,0.005205,0.005290,0.009524,0.007506,0.010612,0.002348,-0.000805,0.007061
2020-01-03,-0.007064,-0.009964,0.005208,-0.010312,0.027081,0.010396,-0.006855,-0.015282,0.002040,0.002486,...,-0.001453,-0.024867,-0.004983,-0.002818,-0.012573,-0.008877,0.001110,-0.002740,0.002298,0.000947
2020-01-06,-0.019163,-0.012959,-0.010050,-0.012738,0.020138,-0.016319,-0.016538,-0.009547,-0.001883,-0.022388,...,-0.005669,0.007109,-0.016566,-0.010638,-0.011409,-0.015901,-0.019331,-0.004321,-0.007487,-0.005830
2020-01-07,0.006969,0.008179,0.002882,0.011864,-0.010569,-0.011030,0.001075,0.002643,0.000314,0.002958,...,-0.002928,0.002497,0.002255,0.006751,0.019231,0.008328,-0.007667,0.001967,-0.008593,-0.002860

In [16]:
fst = True 
for t in stcks:
    if fst: 
        sdData = pd.DataFrame(ek.get_timeseries(t, start_date='2013-12-01', end_date='2018-12-01')['CLOSE'])
        sdData['Ticker'] = t.replace('.L','')
        fst = False
    else: 
        d = pd.DataFrame(ek.get_timeseries(t, start_date='2013-12-01', end_date='2018-12-01')['CLOSE'])
        d['Ticker'] = t.replace('.L','')
        sdData = sdData.append(d)
        time.sleep(0.2)

sdData.columns = ['Price', 'Ticker']
sdData['SRet'] = np.log(sdData.Price / sdData.Price.shift())
sdData

sdrets = sdData.reset_index().pivot('Date', 'Ticker', 'SRet')
sdrets

sd = pd.DataFrame(sdrets.std()).reset_index()
sd['Mean'] = pd.DataFrame(sdrets.mean()).reset_index()[0]
sd.columns = ['Ticker', 'SD', 'SMean']
sd

pd.merge(sData.reset_index(), sd)

/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:282: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.array(timeseries['dataPoints'])
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:284: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  timestamps = pd.np.array([tz_replacer(value) for value in datapoints[:, timestamp_index]],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:286: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  datapoints = pd.np.delete(datapoints, pd.np.s_[timestamp_index],
/Users/Chris/anaconda3/lib/python3.7/site-packages/eikon/time_series.py:209: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data_frame = data_frame.fillna(pd.np.nan)

           Date    Price Ticker      SRet        SD     SMean
0    2018-12-03  1675.40    AAL       NaN  0.031292  0.000152
1    2018-12-04  1660.00    AAL -0.009234  0.031292  0.000152
2    2018-12-05  1625.00    AAL -0.021310  0.031292  0.000152
3    2018-12-06  1556.40    AAL -0.043132  0.031292  0.000152
4    2018-12-07  1607.80    AAL  0.032491  0.031292  0.000152
...         ...      ...    ...       ...       ...       ...
7447 2019-12-31   146.76    VOD -0.012594  0.083355 -0.002541
7448 2020-01-02   147.80    VOD  0.007061  0.083355 -0.002541
7449 2020-01-03   147.94    VOD  0.000947  0.083355 -0.002541
7450 2020-01-06   147.08    VOD -0.005830  0.083355 -0.002541
7451 2020-01-07   146.66    VOD -0.002860  0.083355 -0.002541

[7452 rows x 6 columns]

In [17]:
sData = pd.merge(sData.reset_index(), sd)
sData = sData.set_index('Date')
sData

              Price Ticker      SRet        SD     SMean
Date
2018-12-03  1675.40    AAL       NaN  0.031292  0.000152
2018-12-04  1660.00    AAL -0.009234  0.031292  0.000152
2018-12-05  1625.00    AAL -0.021310  0.031292  0.000152
2018-12-06  1556.40    AAL -0.043132  0.031292  0.000152
2018-12-07  1607.80    AAL  0.032491  0.031292  0.000152
...             ...    ...       ...       ...       ...
2019-12-31   146.76    VOD -0.012594  0.083355 -0.002541
2020-01-02   147.80    VOD  0.007061  0.083355 -0.002541
2020-01-03   147.94    VOD  0.000947  0.083355 -0.002541
2020-01-06   147.08    VOD -0.005830  0.083355 -0.002541
2020-01-07   146.66    VOD -0.002860  0.083355 -0.002541

[7452 rows x 5 columns]

In [18]:
sData.to_csv('sPrices.csv')
pd.read_csv('sPrices.csv')

            Date    Price Ticker      SRet        SD     SMean
0     2018-12-03  1675.40    AAL       NaN  0.031292  0.000152
1     2018-12-04  1660.00    AAL -0.009234  0.031292  0.000152
2     2018-12-05  1625.00    AAL -0.021310  0.031292  0.000152
3     2018-12-06  1556.40    AAL -0.043132  0.031292  0.000152
4     2018-12-07  1607.80    AAL  0.032491  0.031292  0.000152
...          ...      ...    ...       ...       ...       ...
7447  2019-12-31   146.76    VOD -0.012594  0.083355 -0.002541
7448  2020-01-02   147.80    VOD  0.007061  0.083355 -0.002541
7449  2020-01-03   147.94    VOD  0.000947  0.083355 -0.002541
7450  2020-01-06   147.08    VOD -0.005830  0.083355 -0.002541
7451  2020-01-07   146.66    VOD -0.002860  0.083355 -0.002541

[7452 rows x 6 columns]

In [4]:
def getRets(t, s, e):
    return rets.loc[s:e, t]

In [5]:
getRets('AAL', '2018-12-11', '2019-1-1').kurt()+3
getRets('AAL', '2018-12-11', '2019-1-1').skew()

NameError: name 'rets' is not defined

In [ ]:
getRets(sData['Ticker'][0], sData.index[1], sData.index[10]).mean()

In [23]:
gLag = pd.read_csv('GroupedOpData.csv')
gLag

,Ticker,Date,EXPIR_DATE,PUTCALLIND,meanPDF,lagMean,varPDF,lagVar,skewPDF,lagSkew,...,l2Skew,l2Kurt,l3Mean,l3Var,l3Skew,l3Kurt,l10Mean,l10Var,l10Skew,l10Kurt
0,AAL,2019-01-02,2020-12-18,CALL,-0.018267,-0.028250,0.016640,0.016814,0.166943,0.172751,...,0.263810,1.547893,-0.199199,0.035860,0.278474,1.509739,-0.123412,0.037990,0.621406,1.274484
1,AAL,2019-01-02,2020-12-18,PUT,-0.009917,-0.019313,0.015102,0.015118,0.073280,0.067280,...,0.075849,1.608911,-0.199305,0.035581,0.089827,1.609961,-0.075710,0.028091,0.179222,1.442458
2,AAL,2019-01-03,2020-12-18,CALL,-0.007039,-0.018267,0.016166,0.016640,0.092471,0.166943,...,0.172751,1.548393,-0.203825,0.034456,0.263810,1.547893,-0.127184,0.038829,0.648336,1.263356
3,AAL,2019-01-03,2020-12-18,PUT,0.000624,-0.009917,0.015042,0.015102,0.026148,0.073280,...,0.067280,1.679065,-0.209679,0.037146,0.075849,1.608911,-0.076620,0.028400,0.187793,1.422220
4,AAL,2019-01-04,2020-12-18,CALL,-0.027427,-0.007039,0.017096,0.016166,0.138499,0.092471,...,0.166943,1.582593,-0.028250,0.016814,0.172751,1.548393,-0.137062,0.039843,0.676968,1.251158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23216,VOD,2020-01-07,2020-12-18,PUT,-0.227483,-0.156726,0.063772,0.035674,0.279070,0.593010,...,0.204899,1.315143,-0.162427,0.032222,0.573901,0.629171,-0.055520,0.020144,0.353097,1.248708
23217,VOD,2020-01-07,2021-06-18,CALL,-0.087126,-0.088564,0.030155,0.031125,0.348776,0.294643,...,0.219525,1.305814,-0.065163,0.022419,0.435255,0.896721,-0.028089,0.017399,-0.027386,1.749556
23218,VOD,2020-01-07,2021-06-18,PUT,-0.114870,-0.117878,0.036597,0.039684,0.346096,0.391759,...,0.395010,1.166391,-0.120915,0.037893,0.412091,1.184332,NaN,NaN,NaN,NaN
23219,VOD,2020-01-07,2021-12-17,CALL,-0.080600,-0.079303,0.018632,0.018792,0.533941,0.469049,...,0.458905,1.208581,-0.049362,0.011970,0.344211,1.351634,-0.009488,0.017977,0.051232,1.759195
23220,VOD,2020-01-07,2021-12-17,PUT,-0.078677,-0.064958,0.016434,0.014274,0.321261,0.354838,...,0.397636,1.295442,-0.062706,0.014098,0.346976,1.314201,NaN,NaN,NaN,NaN

In [24]:
gLag['pMean'] = gLag.apply(lambda x: getRets(x['Ticker'], x['Date'], x['EXPIR_DATE']).mean(), axis=1)
gLag['pVar'] = gLag.apply(lambda x: getRets(x['Ticker'], x['Date'], x['EXPIR_DATE']).var(), axis=1)
gLag['pSkew'] = gLag.apply(lambda x: getRets(x['Ticker'], x['Date'], x['EXPIR_DATE']).skew(), axis=1)
gLag['pKurt'] = gLag.apply(lambda x: getRets(x['Ticker'], x['Date'], x['EXPIR_DATE']).kurt()+3, axis=1)
gLag

,Ticker,Date,EXPIR_DATE,PUTCALLIND,meanPDF,lagMean,varPDF,lagVar,skewPDF,lagSkew,...,l3Skew,l3Kurt,l10Mean,l10Var,l10Skew,l10Kurt,pMean,pVar,pSkew,pKurt
0,AAL,2019-01-02,2020-12-18,CALL,-0.018267,-0.028250,0.016640,0.016814,0.166943,0.172751,...,0.278474,1.509739,-0.123412,0.037990,0.621406,1.274484,0.000824,0.000283,-0.175798,3.228308
1,AAL,2019-01-02,2020-12-18,PUT,-0.009917,-0.019313,0.015102,0.015118,0.073280,0.067280,...,0.089827,1.609961,-0.075710,0.028091,0.179222,1.442458,0.000824,0.000283,-0.175798,3.228308
2,AAL,2019-01-03,2020-12-18,CALL,-0.007039,-0.018267,0.016166,0.016640,0.092471,0.166943,...,0.263810,1.547893,-0.127184,0.038829,0.648336,1.263356,0.000912,0.000282,-0.183654,3.252569
3,AAL,2019-01-03,2020-12-18,PUT,0.000624,-0.009917,0.015042,0.015102,0.026148,0.073280,...,0.075849,1.608911,-0.076620,0.028400,0.187793,1.422220,0.000912,0.000282,-0.183654,3.252569
4,AAL,2019-01-04,2020-12-18,CALL,-0.027427,-0.007039,0.017096,0.016166,0.138499,0.092471,...,0.172751,1.548393,-0.137062,0.039843,0.676968,1.251158,0.000998,0.000281,-0.191743,3.276617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23216,VOD,2020-01-07,2020-12-18,PUT,-0.227483,-0.156726,0.063772,0.035674,0.279070,0.593010,...,0.573901,0.629171,-0.055520,0.020144,0.353097,1.248708,-0.002860,NaN,NaN,NaN
23217,VOD,2020-01-07,2021-06-18,CALL,-0.087126,-0.088564,0.030155,0.031125,0.348776,0.294643,...,0.435255,0.896721,-0.028089,0.017399,-0.027386,1.749556,-0.002860,NaN,NaN,NaN
23218,VOD,2020-01-07,2021-06-18,PUT,-0.114870,-0.117878,0.036597,0.039684,0.346096,0.391759,...,0.412091,1.184332,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN
23219,VOD,2020-01-07,2021-12-17,CALL,-0.080600,-0.079303,0.018632,0.018792,0.533941,0.469049,...,0.344211,1.351634,-0.009488,0.017977,0.051232,1.759195,-0.002860,NaN,NaN,NaN
23220,VOD,2020-01-07,2021-12-17,PUT,-0.078677,-0.064958,0.016434,0.014274,0.321261,0.354838,...,0.346976,1.314201,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN

In [25]:
gLag.isna().sum()

Ticker          0
Date            0
EXPIR_DATE      0
PUTCALLIND      0
meanPDF         0
lagMean         0
varPDF          0
lagVar          0
skewPDF         0
lagSkew         0
kurtPDF         0
lagKurt         0
leadMean        1
leadVar         1
leadSkew        1
leadKurt        1
zScore          0
l2Mean          1
l2Var           1
l2Skew          1
l2Kurt          1
l3Mean          2
l3Var           2
l3Skew          2
l3Kurt          2
l10Mean         9
l10Var          9
l10Skew         9
l10Kurt         9
pMean           0
pVar          204
pSkew         408
pKurt         612
dtype: int64

In [28]:
gLag

,Ticker,Date,EXPIR_DATE,PUTCALLIND,meanPDF,lagMean,varPDF,lagVar,skewPDF,lagSkew,...,l3Skew,l3Kurt,l10Mean,l10Var,l10Skew,l10Kurt,pMean,pVar,pSkew,pKurt
0,AAL,2019-01-02,2020-12-18,CALL,-0.018267,-0.028250,0.016640,0.016814,0.166943,0.172751,...,0.278474,1.509739,-0.123412,0.037990,0.621406,1.274484,0.000824,0.000283,-0.175798,3.228308
1,AAL,2019-01-02,2020-12-18,PUT,-0.009917,-0.019313,0.015102,0.015118,0.073280,0.067280,...,0.089827,1.609961,-0.075710,0.028091,0.179222,1.442458,0.000824,0.000283,-0.175798,3.228308
2,AAL,2019-01-03,2020-12-18,CALL,-0.007039,-0.018267,0.016166,0.016640,0.092471,0.166943,...,0.263810,1.547893,-0.127184,0.038829,0.648336,1.263356,0.000912,0.000282,-0.183654,3.252569
3,AAL,2019-01-03,2020-12-18,PUT,0.000624,-0.009917,0.015042,0.015102,0.026148,0.073280,...,0.075849,1.608911,-0.076620,0.028400,0.187793,1.422220,0.000912,0.000282,-0.183654,3.252569
4,AAL,2019-01-04,2020-12-18,CALL,-0.027427,-0.007039,0.017096,0.016166,0.138499,0.092471,...,0.172751,1.548393,-0.137062,0.039843,0.676968,1.251158,0.000998,0.000281,-0.191743,3.276617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23216,VOD,2020-01-07,2020-12-18,PUT,-0.227483,-0.156726,0.063772,0.035674,0.279070,0.593010,...,0.573901,0.629171,-0.055520,0.020144,0.353097,1.248708,-0.002860,NaN,NaN,NaN
23217,VOD,2020-01-07,2021-06-18,CALL,-0.087126,-0.088564,0.030155,0.031125,0.348776,0.294643,...,0.435255,0.896721,-0.028089,0.017399,-0.027386,1.749556,-0.002860,NaN,NaN,NaN
23218,VOD,2020-01-07,2021-06-18,PUT,-0.114870,-0.117878,0.036597,0.039684,0.346096,0.391759,...,0.412091,1.184332,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN
23219,VOD,2020-01-07,2021-12-17,CALL,-0.080600,-0.079303,0.018632,0.018792,0.533941,0.469049,...,0.344211,1.351634,-0.009488,0.017977,0.051232,1.759195,-0.002860,NaN,NaN,NaN
23220,VOD,2020-01-07,2021-12-17,PUT,-0.078677,-0.064958,0.016434,0.014274,0.321261,0.354838,...,0.346976,1.314201,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN

In [27]:
gLag.to_csv('pGroupData.csv', index=False)
pd.read_csv('pGroupData.csv')

,Ticker,Date,EXPIR_DATE,PUTCALLIND,meanPDF,lagMean,varPDF,lagVar,skewPDF,lagSkew,...,l3Skew,l3Kurt,l10Mean,l10Var,l10Skew,l10Kurt,pMean,pVar,pSkew,pKurt
0,AAL,2019-01-02,2020-12-18,CALL,-0.018267,-0.028250,0.016640,0.016814,0.166943,0.172751,...,0.278474,1.509739,-0.123412,0.037990,0.621406,1.274484,0.000824,0.000283,-0.175798,3.228308
1,AAL,2019-01-02,2020-12-18,PUT,-0.009917,-0.019313,0.015102,0.015118,0.073280,0.067280,...,0.089827,1.609961,-0.075710,0.028091,0.179222,1.442458,0.000824,0.000283,-0.175798,3.228308
2,AAL,2019-01-03,2020-12-18,CALL,-0.007039,-0.018267,0.016166,0.016640,0.092471,0.166943,...,0.263810,1.547893,-0.127184,0.038829,0.648336,1.263356,0.000912,0.000282,-0.183654,3.252569
3,AAL,2019-01-03,2020-12-18,PUT,0.000624,-0.009917,0.015042,0.015102,0.026148,0.073280,...,0.075849,1.608911,-0.076620,0.028400,0.187793,1.422220,0.000912,0.000282,-0.183654,3.252569
4,AAL,2019-01-04,2020-12-18,CALL,-0.027427,-0.007039,0.017096,0.016166,0.138499,0.092471,...,0.172751,1.548393,-0.137062,0.039843,0.676968,1.251158,0.000998,0.000281,-0.191743,3.276617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23216,VOD,2020-01-07,2020-12-18,PUT,-0.227483,-0.156726,0.063772,0.035674,0.279070,0.593010,...,0.573901,0.629171,-0.055520,0.020144,0.353097,1.248708,-0.002860,NaN,NaN,NaN
23217,VOD,2020-01-07,2021-06-18,CALL,-0.087126,-0.088564,0.030155,0.031125,0.348776,0.294643,...,0.435255,0.896721,-0.028089,0.017399,-0.027386,1.749556,-0.002860,NaN,NaN,NaN
23218,VOD,2020-01-07,2021-06-18,PUT,-0.114870,-0.117878,0.036597,0.039684,0.346096,0.391759,...,0.412091,1.184332,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN
23219,VOD,2020-01-07,2021-12-17,CALL,-0.080600,-0.079303,0.018632,0.018792,0.533941,0.469049,...,0.344211,1.351634,-0.009488,0.017977,0.051232,1.759195,-0.002860,NaN,NaN,NaN
23220,VOD,2020-01-07,2021-12-17,PUT,-0.078677,-0.064958,0.016434,0.014274,0.321261,0.354838,...,0.346976,1.314201,NaN,NaN,NaN,NaN,-0.002860,NaN,NaN,NaN